FROM ubuntu:16.04
MAINTAINER NSCPX-Dev <NSCPX-Dev@citrite.net>
RUN apt-get update -y 
RUN apt-get install -y python
RUN apt-get install -y python-pip
RUN pip install netaddr 
RUN pip install pyyaml 
RUN pip install requests[security]

ADD triton_ingress.tar.gz /var
COPY triton_startup.sh /var/triton_startup.sh
ENV NS_CONFIG_FRONT_END TRUE
ENV NS_TYPE VPX
ENV NS_USER nsroot
ENV NS_PASSWORD nsroot
ENV NS_PROTOCOL HTTPS
ENV NS_PORT 443
ENV LOGLEVEL INFO
RUN mkdir -p /var/mps/tenants/root/ns_ssl_certs/
RUN mkdir -p /var/mps/tenants/root/ns_ssl_keys/


#Setup tools for service-discovery.
RUN mkdir -p /tmp
RUN (cd /tmp  && mv /var/triton_ingress/nitro-python.tar . &&\
	tar xf nitro-python.tar && \
	cd nitro-python-* && \
	python setup.py install >> /dev/null && \
	cd / && \
	rm -rf /tmp/ns-11.0-63.16* && \
	rm -rf /tmp/ns_nitro-python* && \
	rm -rf /tmp/nitro-python-* )

CMD ["bash", "/var/triton_startup.sh"]
