all:
	sudo docker build --force-rm=true --no-cache=true --rm=true -f Dockerfile_triton_alpine -t triton:4.0 . 
triton-nsoslx:
	sudo docker build --force-rm=true --no-cache=true --rm=true -f Dockerfile_triton_nsoslx -t triton_nsoslx:4.0 .
triton-ubuntu:
	sudo docker build --force-rm=true --no-cache=true --rm=true -f Dockerfile_triton_ubuntu -t triton_ubuntu:4.0 .
